#!/bin/bash -l

################################################################################
#Script Name: 
#Description: 
#Args       : None 
#Author     : Georgia Doing
#Email      : georgia.doing@duke.edu
################################################################################


#SBATCH --job-name=aec
#SBATCH --time=0-23:00:00
#SBATCH --ntasks=1
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=georgia.doing@duke.edu
#SBATCH -o /work/gd134/oe/%u-%x-%A-%a
#SBATCH --mem-per-cpu=512G







cd $SLURM_SUBMIT_DIR

conda activate radage

#Rscript ensemble_construction_p_dcc.R ../data_files/ecmgp_lcn01.csv \
/work/gd134/adage_models/ /work/gd134/scratch 450 571 670 735 'weighted' /work/gd134/adage_models /work/gd134/wcor_ec_mgp_450.csv


Rscript ensemble_construction_p_dcc.R ../data_files/ecmg_mgsp_lcn01.csv \
/work/gd134/adage_models/ /work/gd134/scratch 450 672 771 735 'weighted' /work/gd134/adage_models /work/gd134/wcor_ec_mg_mgsp_450.csv
